
name: Helm Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Helm Upgrade
      run: helm upgrade --install etl-platform ./helm
