
name: Terraform Dev Deploy

on:
  push:
    branches:
      - develop

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: infra-provisioning

    - name: Terraform Validate
      run: terraform validate
      working-directory: infra-provisioning

    - name: Terraform Plan
      run: terraform plan -var-file=environments/dev/dev.tfvars
      working-directory: infra-provisioning

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file=environments/dev/dev.tfvars
      working-directory: infra-provisioning
